studProfkom/Controllers/NewsController.cs
using studProfkom.Models;
using System;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace studProfkom.Controllers
{
	public class NewsController : Controller
	{
		private EFDbContext _repository;

		public NewsController()
		{
			_repository = new EFDbContext();
		}

		[HttpGet]
		[Authorize]
		public ActionResult EditOrCreateArticle(int id)
		{
			if (id == 0)
			{
				return View(new NewsArticleViewModel());
			}
			else
			{
				var n = _repository.NewsArticles.SingleOrDefault(x => x.Id == id);
				if (n != null)
				{
					return View(new NewsArticleViewModel
					{
						Id = n.Id,
						ArticleShortDescription = n.ArticleShortDescription,
						EventShortDescription = n.EventShortDescription,
						EventStartDate = n.EventStartDate.HasValue ? new DateTime(1970, 1, 1, 0, 0, 0, 0).AddSeconds(n.EventStartDate.Value).ToString("dd.MM.yyyy") : "",
						EventStartTime = n.EventStartDate.HasValue ? new DateTime(1970, 1, 1, 0, 0, 0, 0).AddSeconds(n.EventStartDate.Value).ToString("HH:mm") : "",
						GooglePlusAlbumId = n.GooglePlusAlbumId,
						GooglePlusUserId = n.GooglePlusUserId,
						ImageName = n.ImageName,
						IsEvent = n.IsEvent,
						PublicationDate = new DateTime(1970, 1, 1, 0, 0, 0, 0).AddSeconds(n.PublicationDate).ToString("dd.MM.yyyy HH:mm"),
						Text = n.Text,
						Title = n.Title
					});
				}
				else
				{
					return View(new NewsArticleViewModel());
				}
			}
		}

		[HttpPost]
		[Authorize]
		public ActionResult Save(NewsArticleViewModel article,
									   [Required, FileExtensions(ErrorMessage = "Картинка має бути формату: *.jpg або *.png", Extensions = "jpg, png")]
									   HttpPostedFileBase articleImage)
		{
			if (ModelState.IsValid)
			{
				NewsArticle n;

				if (_repository.NewsArticles.Any(x => x.Id == article.Id))
				{
					n = _repository.NewsArticles.Single(x => x.Id == article.Id);
				}
				else
				{
					n = new NewsArticle();
				}

				if (articleImage != null && articleImage.ContentLength > 0)
				{
					if (!System.IO.File.Exists(Server.MapPath(articleImage.FileName)))
					{
						if (n.Id != 0 && !_repository.NewsArticles.Any(x => x.ImageName == n.ImageName && x.Id != n.Id))
						{
							System.IO.File.Delete(Server.MapPath("~/Content/Images/Articles/" + n.ImageName));
						}
						articleImage.SaveAs(Server.MapPath("~/Content/Images/Articles/" + articleImage.FileName));
					}
					else
					{
						if (!_repository.NewsArticles.Any(x => x.ImageName == articleImage.FileName && x.Id != n.Id))
						{
							System.IO.File.Delete(Server.MapPath("~/Content/Images/Articles/" + articleImage.FileName));
						}
					}
					n.ImageName = articleImage.FileName;
				}
				else
				{
					if (String.IsNullOrEmpty(n.ImageName))
					{
						ModelState.AddModelError("", "Зображення не обрано");

						return RedirectToAction("EditOrCreateArticle", article);
					}
				}

				n.ArticleShortDescription = article.ArticleShortDescription;
				n.EventShortDescription = article.EventShortDescription;
				n.EventStartDate = String.IsNullOrEmpty(article.EventStartDate) ? 
					0 : (DateTime.ParseExact(String.Format("{0} {1}", article.EventStartDate, String.IsNullOrEmpty(article.EventStartTime) ? 
					"00:00" : 
					article.EventStartTime), "dd.MM.yyyy HH:mm", CultureInfo.InvariantCulture).Ticks  - new DateTime(1970, 1, 1, 0, 0, 0, 0).Ticks) / TimeSpan.TicksPerSecond;
				n.PublicationDate = (DateTime.Now.Ticks - new DateTime(1970, 1, 1, 0, 0, 0, 0).Ticks) / TimeSpan.TicksPerSecond;
				n.GooglePlusAlbumId = article.GooglePlusAlbumId;
				n.GooglePlusUserId = article.GooglePlusUserId;
				n.IsEvent = article.IsEvent;
				n.Text = article.Text;
				n.Title = article.Title;

				if (n.Id == 0)
				{
					_repository.NewsArticles.Add(n);
				}

				_repository.SaveChanges();

				return RedirectToAction("Index", "Home");
			}
			else
			{
				return RedirectToAction("EditOrCreateArticle", article);
			}
			return View(article);
		}

		[Authorize]
		public ActionResult Remove(int id)
		{
			string returnUrl = HttpContext.Request.UrlReferrer.ToString();

			var article = _repository.NewsArticles.Single(x => x.Id == id);
			if (article == null)
			{
				return RedirectToAction("Index", "Home");
			}
			_repository.NewsArticles.Remove(article);
			_repository.SaveChanges();

			Uri uri;
			if (!string.IsNullOrEmpty(returnUrl) && Uri.TryCreate(returnUrl, UriKind.RelativeOrAbsolute, out uri))
			{
				return Redirect(returnUrl);
			}
			return RedirectToAction("Index", "Home");
		}

		[Authorize]
		public ActionResult CancelArticle()
		{
			return RedirectToAction("Index", "Home");
		}
	}
}

studProfkom/Views/News/EditOrCreateArticle.cshtml
@model studProfkom.Models.NewsArticleViewModel
@{
    ViewBag.Title = "Студпрофком УАД - Додати новину";
    Layout = "~/Views/_mainLayout.cshtml";
}


@using System.Web.Optimization

@section CSSIncludes
{
    @Styles.Render("~/content/admin/css")
}

@section JSIncludes
{
    <script src="@Url.Content("~/Content/Scripts/tinymce/tinymce.min.js")"></script>
    @Scripts.Render("~/content/admin/js")
}

<div class="add-article-wrapper">
    <h3>Додати <span>новину</span> або <span>подію</span></h3>

    @using (Html.BeginForm("Save", "News", FormMethod.Post, new { enctype = "multipart/form-data" }))
    { 
        
        @Html.HiddenFor(model => model.Id)
        @Html.Hidden("returnUrl", (string)ViewBag.returnUrl)

        @Html.ValidationSummary(false)

        <fieldset>
            <div class="editor-field">
                <div class="editor-label">Назва: </div>
                @Html.EditorFor(x => x.Title)
            </div>
            <div class="editor-field">
                <div class="editor-label">Чи це подія? </div>
                @Html.EditorFor(x=>x.IsEvent)
            </div>
            <div class="editor-field">
                <div class="editor-label">Картинка: </div>
                <input type="file" name="articleImage" id="articleImage"/>
            </div>
            @if (!String.IsNullOrEmpty(Model.ImageName))
            {
                <div class="editor-field image-select">
                    <div class="editor-label">Поточна картинка: </div>
                    <img src="@Url.Content("~/Content/Images/Articles/" + Model.ImageName)" alt="" class="article-image-preview"/>
                </div>
            }
            <div class="editor-field">
                <div class="editor-label">Короткий опис новини: </div>
                @Html.EditorFor(model => model.ArticleShortDescription)
            </div>
            <div class="editor-field">
                <div class="editor-label">Початок події: </div>
                @Html.EditorFor(x=>x.EventStartDate)
                @Html.EditorFor(x=>x.EventStartTime)
            </div>
            <div class="editor-field">
                <div class="editor-label">Короткий опис події: </div>
                @Html.EditorFor(model => model.EventShortDescription)
            </div>
            <div class="editor-field">         
                <div class="editor-label google-pluss-album">Google+ ID користувача: </div>
                @Html.EditorFor(model => model.GooglePlusUserId)
            </div>
           
            <div class="editor-field">  
                <div class="editor-label google-pluss-album">Google+ ID альбому: </div>
                @Html.EditorFor(model => model.GooglePlusAlbumId)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Text, "Текст: ")
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.Text, new { @class = "article-text" })
            </div>
            <div>
                <button type="submit">Зберегти</button>
                <a href="@Url.Action("CancelArticle", "Home")"><button>Відмінити</button></a>
            </div>
        </fieldset>
    }
</div>