studProfkom/Controllers/ProfkomController.cs
using studProfkom.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace studProfkom.Controllers
{
  public class ProfkomController : Controller
  {
    //
    // GET: /Profkom/
    private EFDbContext _repository;

    public ProfkomController()
    {
      _repository = new EFDbContext();
    }

    public ActionResult Guidance()
    {
      return View();
    }
    public ActionResult Profbureau()
    {
      return View();
    }
    public ActionResult About()
    {
      return View();
    }
    public ActionResult Orphans()
    {
      return View();
    }
    public ActionResult Chummeries()
    {
      var list = new List<Faculty>();
      ViewBag.Faculties = new List<Faculty>();
      ViewBag.Faculties.Add(new Faculty{Id = 0, Name = "Виберіть факультет зі списку"});
      ViewBag.Faculties.AddRange(_repository.Faculties.OrderBy(x => x.Name).ToList());

      return View(_repository.Applications.ToList());
    }
    public ActionResult Students()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Application(Application app)
    {
      if (ModelState.IsValid && app.FacultyId != 0)
      {
        _repository.Applications.Add(new Application
        {
          FullName = app.FullName,
          Faculty = _repository.Faculties.FirstOrDefault(x => x.Id == app.FacultyId),
          City = app.City,
          Phone = app.Phone,
          CreateDate = DateTime.Now
        });
        _repository.SaveChanges();

        return Json(new { message = "success", text = "Заявку успішно надіслано." }, JsonRequestBehavior.AllowGet);
      }
      else
      {
        return Json(new { 
          error = "validation error",
          message = "Усі поля є обов'язковими"
        }, JsonRequestBehavior.AllowGet);
      }
    }
    [Authorize]
    public ActionResult StudentsApplications()
    {
      return View(_repository.Applications.OrderByDescending(x => x.CreateDate).ToList());
    }
  }
}

studProfkom/Views/Profkom/About.cshtml
@{
    ViewBag.Title = "Студпрофком УАД - Про нас";
    Layout = "~/Views/_mainLayout.cshtml";
}

<div class="about-wrapper">
    <h3>ПРО <span>НАС</span></h3>
    @*<img class="project-logo" src="@Url.Content("~/Content/Images/Projects/miss-uad-logo.jpg")" />*@
    <p>
        В Українській академії друкарства важливу роль щодо соціального захисту прав студентів та 
        організації дозвілля відіграє первинна профспілкова організація студентів (профком студентів). 
        Ця громадська організація входить до профспілки працівників освіти і науки України, що є 
        всеукраїнською добровільною неприбутковою громадською організацією, яка об’єднує людей на 
        добровільних засадах без жодних обмежень.
    </p>
    <p>
        Метою діяльності організації є представництво, здійснення та захист трудових, 
        соціально-економічних прав та інтересів своїх членів профспілки.
    </p>
    <p>
        Сьогодні до складу профкому студентів входить профбюро трьох факультетів та
         профбюро Львівського поліграфічного коледжу, працюють комісії соціального 
        захисту, культурно-масової роботи, комісія з питань спорту та туризму, комісія 
        з оздоровлення студентів. 
    </p>
    <p>
        Вже стало доброю традицією щороку проводити свято молодості та краси 
        <strong>«Міс Українська академія друкарства»</strong>, що демонструє високий рівень естетичного, 
        культурного та інтелектуального розвитку прекрасної половини студентства нашої академії. 
    </p>
    <p>
        Разом з Львівською міською радою діє проект <strong>«Стажування студентської молоді»</strong>, 
        відповідно до програми якого студенти академії щорічно мають можливість пройти стажування 
        в органах місцевого самоврядування.
    </p>
    <p>
        Для висвітлення подій, що відбуваються в студентському житті академії, видається 
        студентська газета <strong>«Підголоско’76»</strong>, де студенти мають змогу реалізовувати себе 
        у журналістиці та набувати досвіду на ниві видавничо-поліграфічної справи.
    </p>
    <p>
        Щороку до Великодніх свят проводяться акції: <strong>«Розмалюй писанку»</strong>, <strong>«День вишиванки»</strong>, 
        <strong>«Гаївки в УАД»</strong>.
    </p>
    <p>
        Наші студенти не байдужі до дітей, позбавлених батьківської опіки. Профком студентів здійснює 
        соціальні проекти: <strong>«З Миколаєм прийди – дітям свято принеси!»</strong> 
        (підтримка школи-інтернату для дітей з вадами розумового розвитку), <strong>«Не будь байдужим!»</strong> 
        (підтримка Львівського Геріатричного Інтернату).
    </p>
    <p>
        Для тих студентів, які бажають пізнати нашу країну діє <strong>проект «Подорожуємо разом»</strong>, який дає 
        можливість студентам побувати у найцікавіших місцях нашої країни: замки Львівщини 
        (маршрут <strong>«Золота підкова»</strong> – Олеський, Підгорецький та Золочівський замки), <strong>Почаївська 
        Лавра</strong>, Національний дендрологічний парк <strong>«Софіївка»</strong>, сім чудес України – <strong>Кам’янець-Подільська 
        фортеця</strong> та містом Хотин, <strong>«Замок Паланок» (Мукачеве)</strong> та <strong>замок Шенборна (Чинадійово)</strong>, а ще 
        кожен може взяти участь у <strong>проекті «Перезавантаження»</strong> (щорічне сходження студентів академії 
        на найвищу гору України – Говерлу).
    </p>
    <p>
        Студенти академії є учасниками молодіжних фестивалів: <strong>«Зашків»</strong> (приурочений до дня народження Є. Коновальця),
         <strong>«Бабине Літо»</strong> (міжнародний молодіжний фестиваль  туристичної пісні), а також у фестивалі <strong>«Студентська 
        ліга КВК Львова»</strong> серед вищих навчальних закладів. В академії діє <strong>студентський театр</strong>, 
        де талановита молодь може стати учасниками художньої самодіяльності. Профком студентів 
        не забуває і про закоханих, і тому в день св. Валентина в головному корпусі академії 
        проводиться акція <strong>«Стіна кохання»</strong>, де кожен бажаючий має можливість признатись у своїх почуттях.
    </p>
    <p>
        Від сесії до сесії живуть студенти весело, адже студентське життя полягає не лише в навчанні, а й у 
        відпочинку, тому профком студентів постійно організовує святкові вечірки у нічних клубах (День першокурсника, 
        диско 80-90-х), а також проводить турніри з <strong>«Counter Strike» та пейнтболу</strong> та оформляє абонемент у 
        львівський <strong>аквапарк «Пляж»</strong>.
    </p>
    <p>
        Для заощадження часу та коштів у профкомі студентів можна оформити міжнародну картку <strong>ISIC</strong>
        (єдине міжнародне студентське посвідчення та водночас дисконтна картка) та <strong>«Українську студентську картку»</strong>.
    </p>
    <p>
        Не забуває профком студентів і про спорт. Щороку профспілка виступає співорганізатором багатьох 
        спортивних турнірів таких, як <strong>«Львівська веснянка»</strong>, <strong>«Кубок ректора з міні-футболу»</strong>, 
        <strong>«Кубок ректора зі спортивної аеробіки»</strong>, <strong>«Кубок ректора з шахів»</strong>, команда з лижного спорту 
        щозими має можливість проводити тренувальні збори на схилах Карпат.
    </p>
    <p>
        Чим би не займалися студенти упродовж року, вони завжди очікують літа. <strong>Програма оздоровлення 
        студентів</strong> дає можливість відпочити на узбережжі Чорного моря та провести весело час з друзями.
    </p>
    <p>
        Сьогодні профком студентів УАД тісно співпрацює з профкомами студентів вищих навчальних закладів м. Львова, 
        Кіровоградським національним технічним університетом, Національним аерокосмічним університетом ім. 
        М.Є.Жуковського «ХАІ», Харківським національним університетом радіоелектроніки, Херсонським державним 
        педагогічним університетом та іншими ВНЗ, Асоціацією правозахисних організацій студентів України. 
    </p>
    <p>
        Профспілкова організація студентів є добрим помічником і порадником для усіх студентів академії, 
        адже завжди допоможе та надасть ґрунтовну консультацію.
    </p>
</div>

studProfkom/Views/Profkom/Chummeries.cshtml
@model List<studProfkom.Models.Application>
@{
    ViewBag.Title = "Студпрофком УАД - Гуртожитки";
    Layout = "~/Views/_mainLayout.cshtml";
}

<div class="chummeries-wrapper">
    <h3>
        Гуртожитки <span class="title-caption">що потрібно для успішного поселення</span>
        @if (base.User.Identity.IsAuthenticated)
        {
            @Html.ActionLink("Заявки", "StudentsApplications", "Profkom", null, new { @class = "show-applications-link" })
        }
    </h3>
    <div class="chummerie-guide-wrapper">
      <h2>При поселенні в гуртожиток в наявності потрібно мати наступні документи:</h2>
      <ol>
        <li>Довідка від лікаря-дерматолога.</li>
        <li>Паспорт з відміткою про зняття з реєстраційного обліку за попереднім місцем реєстрації, з двома листками вибуття.</li>
        <li>Фото 3х4 (4 шт).</li>
        <li>Квитанція про оплату за 2015/16 н/р (2280 грн/рік). Зразок квитанції завантажити <a href="@Url.Content("~/Content/Documents/Applications/зразок_квитанції_на_оплату.jpg")" target="_blank">тут</a>.</li>
        <li>Взяти у своєму деканаті ордер на поселення.</li>
        <li>Для військовозобов’язаних необхідно стати на військовий облік (вул. Підголоско, 19, 4 поверх).</li>
        <li>Заповнити форму попередньої реєстрації під цим пунктом:</li>
      </ol>

      <h2>Додаткові документи для військовозобов’язаних вступників:</h2>
      <ol>
        <li>Знятись з військового обліку за місцем реєстрації</li>
        <li>Отримати довідку у військовому обліку УАД (буде працювати під час поселення)</li>
        <li>В паспортиста гуртожитку написати заяву і оформити талони на реєстрацію</li>
      </ol>
    </div>

    <div class="chummerie-application-wrapper">
      <div class="chummerie-application-placeholder">
        <span class="chummerie-application-placeholder-text">
          Наразі подачу заявок призупинено
        </span>
      </div>
      <form class="form">
        <div class="form-group">
          <label for="full-name">ПІБ: </label>
          <input type="text" class="form-control" id="full-name" name="full-name"/>
        </div>
        <div class="form-group">
          <label for="city">Вкажіть звідки ви: </label>
          <input type="text" class="form-control" id="city" name="city"/>
        </div>
        <div class="form-group">
          <label for="faculty">Назва факультету: </label>
          @Html.DropDownList("Faculties", new SelectList(ViewBag.Faculties, "Id", "Name"), new { @class = "form-control", id = "faculty", name = "faculty" })
        </div>
        <div class="form-group">
          <label for="phone">Номер телефону: </label>
          <input type="text" class="form-control" id="phone" name="phone"/>
        </div>
        <button class="btn btn-success" type="reset">Надіслати</button>
        <button class="btn btn-default" type="reset">Очистити</button>
        <div class="submition-indicator"></div>
      </form>
    </div>

    <p>Поселення відбуватиметься по факультетах:</p>
    <ul>
      <li>ВПІТ – 25-26 серпня (гуртожиток №1, вул. Підголоско, 23)</li>
      <li>ЕОКС – 27-28 серпня (гуртожиток №1, вул. Підголоско, 23)</li>
      <li>КПІ – 27-29 серпня (гуртожиток №3, вул. Підголоско, 20)</li>
    </ul>
    <p>За детальною інформацією звертайтесь до комісії з поселення: м. Львів, вул. Підголоско, 19, к.311, тел. 242-23-98, +380930984074.</p>
</div>

studProfkom/Views/Profkom/Guidance.cshtml
@{
    ViewBag.Title = "Студпрофком УАД - Керівництво профкому";
    Layout = "~/Views/_mainLayout.cshtml";
}

<div class="guidance-wrapper">
    <h3>НАШЕ <span>КЕРІВНИЦТВО</span></h3>
    <div class="group-photo"></div>
    <div class="item top">
        <img src="@Url.Content("~/Content/Images/About/head.jpg")" alt=""/>
        <div class="item-info">
            <h4>Любов Любомирівна Тупичак</h4>
            <span class="guidance-position">Голова профкому студентів УАД</span>
        </div>
    </div>
    <div class="item">
        <div class="item-info">
            <h4>Ліліана Гуцуляк</h4>
            <span class="guidance-position">Спеціаліст організаційно-інформаційної роботи</span>
        </div>
        <img src="@Url.Content("~/Content/Images/About/organization-information-specialist.jpg")" alt=""/>
    </div>
    <div class="item">
        <img src="@Url.Content("~/Content/Images/About/student-coop-specialist.jpg")" alt=""/>
        <div class="item-info">
            <h4>Олег Шийка</h4>
            <span class="guidance-position">Спеціаліст по роботі зі студентами</span>
        </div>
    </div>
    <div class="item">
        <div class="item-info">
            <h4>Оля Андрушків</h4>
            <span class="guidance-position">Бухгалтер</span>
        </div>
        <img src="@Url.Content("~/Content/Images/About/booker.jpg")" alt=""/>
    </div>
    <div class="item">
        <img src="@Url.Content("~/Content/Images/About/profkom-work-specialist.jpg")" alt=""/>
        <div class="item-info">
            <h4>Марічка Ільницька</h4>
            <span class="guidance-position">Спеціаліст з профспілкової роботи</span>
        </div>
    </div>
</div>

studProfkom/Views/Profkom/Orphans.cshtml
@{
    ViewBag.Title = "Студпрофком УАД - Сиротам";
    Layout = "~/Views/_mainLayout.cshtml";
}

<div class="orphans-wrapper">
    <h3>Сиротам <span class="title-caption">посилання на корисні документи</span></h3>
    <p>
        <ul>
            <li>
                <a href="@Url.Content("~/Content/Documents/Orphans/КАБІНЕТ-МІНІСТРІВ-УКРАЇНИ.docx")">
                    Постанова Кабінету Міністрів України №226<br />“Про поліпшення виховання, навчання, соціального захисту та матеріального 
                    забезпечення дітей-сиріт і дітей, позбавлених батьківського піклування”
                </a>
            </li>
            <li>
                <a href="@Url.Content("~/Content/Documents/Orphans/КАБІНЕТ-МІНІСТРІВ-УКРАЇНИ-Питання-діяльності-органів-опіки-та-піклування.docx")">
                    Постанова Кабінету Міністрів України №866<br />“Про Питання діяльності органів опіки та піклування,пов’язаної із захистом прав дитини”
                </a>
            </li>
            <li>
                <a href="@Url.Content("~/Content/Documents/Orphans/МІНІСТЕРСТВО-ОСВІТИ-УКРАЇНИ-Про-затвердження-Інструкції-про-виготовлення-і-правила.docx")">
                    Наказ Міністерства Освіти і Науки України №216<br />“Про затвердження Інструкції про виготовлення і правила користування 
                    Єдиним квитком для дітей-сиріт і дітей,які залишилися без піклування”
                </a>
            </li>
        </ul>
    </p>
</div>

studProfkom/Views/Profkom/Profbureau.cshtml
@{
    ViewBag.Title = "Студпрофком УАД - Голови Профбюро";
    Layout = "~/Views/_mainLayout.cshtml";
}

<div class="profbureau-wrapper">
    <h3>ГОЛОВИ <span>ПРОФБЮРО</span></h3>
    <div class="item top">
        <img src="@Url.Content("~/Content/Images/About/economics-book-craft.jpg")" alt=""/>
        <div class="item-info">
            <h4>Ірина Куць</h4>
            <span class="guidance-position">Голова профбюро факультету економіки і організації книжкової справи</span>
        </div>
    </div>
    <div class="item">
        <div class="item-info">
            <h4>Анастасія Дричик</h4>
            <span class="guidance-position">Голова профбюро Львівського поліграфічного коледжу</span>
        </div>
        <img src="@Url.Content("~/Content/Images/About/poligraph-college.jpg")" alt=""/>
    </div>
    <div class="item">
        <img src="@Url.Content("~/Content/Images/About/publish-poligraph-tech.jpg")" alt=""/>
        <div class="item-info">
            <h4>Ірина Щербій</h4>
            <span class="guidance-position">Голова профбюро факультету видавничо-поліграфічних технологій</span>
        </div>
    </div>
</div>

studProfkom/Views/Profkom/Students.cshtml
@{
    ViewBag.Title = "Студпрофком УАД - Студентам";
    Layout = "~/Views/_mainLayout.cshtml";
}

<div class="students-wrapper">
    <h3>Студентам <span class="title-caption">посилання на корисні документи</span></h3>
    <p>
        <ul>
            <li>
                <a href="http://osvita.ua/legislation/Vishya_osvita/3142/print/">
                    Наказ Міністерства Освіти і Науки України №1004<br /> 
                    "Про затвердження Примірного положення про студентський гуртожиток вищого навчального закладу"
                </a>
            </li>
            <li>
                <a href="@Url.Content("~/Content/Documents/Orphans/КАБІНЕТ-МІНІСТРІВ-УКРАЇНИ-Питання-діяльності-органів-опіки-та-піклування.docx")">
                    Лист Міністерства Освіти і Науки України від 14.09.2011, №1/9-705<br />
                    “Про недопущення обмежень прав мешканців студентських гуртожитків”
                </a>
            </li>
            <li>
                Заява на вступ у профспілку:
                <a href="@Url.Content("~/Content/Documents/Applications/Заява_на_вступ.doc")">
                    Скачати документ.
                </a>
            </li>
        </ul>
    </p>
</div>

studProfkom/Views/Profkom/StudentsApplications.cshtml
@model List<studProfkom.Models.Application>
@{
  ViewBag.Title = "Студпрофком УАД - Заявки студентів на поселення у гуртожитки";
  Layout = "~/Views/_mainLayout.cshtml";
}

<div class="chummery-applications-wrapper">
  <h3>Заявки <span>студентів</span><a href="#" class="show-applications-link print-btn">Друкувати</a></h3>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="table-id-header">
          №
        </th>
        <th>
          ПІБ
        </th>
        <th>
          Місто
        </th>
        <th class="table-faculty-header">
          Факультет
        </th>
        <th class="table-phone-header">
          Телефон
        </th>
        <th>
          Дата подачі
        </th>
      </tr>
    </thead>
    <tbody>
      @if (Model.Count > 0)
      {
        for (int i = 0; i < Model.Count(); i++)
        {
          <tr>
            <td>
              @(i + 1)
            </td>
            <td title="@Model[i].FullName">
              @Model[i].FullName
            </td>
            <td title="@Model[i].City">
              @Model[i].City
            </td>
            <td title="@Model[i].Faculty.Name">
              @Model[i].Faculty.Name
            </td>
            <td title="@Model[i].Phone">
              @Model[i].Phone
            </td>
            <td title="@String.Format("{0:d/MM/yyyy  HH:mm:ss}", Model[i].CreateDate)">
              @String.Format("{0:d/MM/yyyy  HH:mm:ss}", Model[i].CreateDate)
            </td>
          </tr>
        }
      }
      else
      {
        <tr>
          <td colspan="4">Наразі жодної заявки</td>
        </tr>
      }
    </tbody>
  </table>
</div>

<script>
  document.querySelector('.print-btn').onclick = function() {
    window.print();
  };
</script>