studProfkom/Controllers/PidholoskoMagazineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using studProfkom.Models;
using System.IO;
using System.Text.RegularExpressions;

namespace studProfkom.Controllers
{
	public class PidholoskoMagazineController : Controller
	{
		//
		// GET: /PidholoskoMagazine/
		private static List<pidholoskoMagazineIssue> _pidholoskoIssueList = new List<pidholoskoMagazineIssue>();

		public ActionResult Archive()
		{
			_pidholoskoIssueList.Clear();
			ScanForIssues();
			return View(_pidholoskoIssueList);
		}
		[HttpGet, Authorize]
		public ActionResult AddIssue()
		{
			return View();
		}
		[HttpPost, Authorize]
		public ActionResult AddIssue(HttpPostedFileBase issueFile, HttpPostedFileBase issueCover)
		{
			if (issueFile != null && issueCover != null)
			{
				if (Path.GetFileNameWithoutExtension(issueFile.FileName) == Path.GetFileNameWithoutExtension(issueCover.FileName))
				{
					if (!System.IO.File.Exists(Path.Combine(Server.MapPath("~/Content/Magazine"), issueFile.FileName)) &&
						!System.IO.File.Exists(Path.Combine(Server.MapPath("~/Content/Magazine"), issueCover.FileName)))
					{
						if (Path.GetExtension(issueFile.FileName) == ".pdf")
						{
							if (issueFile.ContentLength > 0)
							{
								var fileName = issueFile.FileName;
								var path = Path.Combine(Server.MapPath("~/Content/Magazine"), fileName);
								issueFile.SaveAs(path);
							}

						}
						else
						{
							ModelState.AddModelError("Помилка", "Файл журналу має бути у форматі - *.pdf.");
							return View();
						}
						if (Path.GetExtension(issueCover.FileName) == ".jpg" || Path.GetExtension(issueCover.FileName) == ".png")
						{
							if (issueCover.ContentLength > 0)
							{
								var fileName = issueCover.FileName;
								var path = Path.Combine(Server.MapPath("~/Content/Magazine"), fileName);
								issueCover.SaveAs(path);
							}
						}
						else
						{
							ModelState.AddModelError("Помилка", "Файл обкладинки має бути у форматі - *.jpg або *.png.");
							return View();
						}
						return RedirectToAction("Archive", "pidholoskoMagazine");
					}

					ModelState.AddModelError("Помилка", "Один або кілька файлів вже присутні у базі");
					return View();
				}

				ModelState.AddModelError("Помилка", "Файли мають різні імена");
				return View();
			}
			ModelState.AddModelError("Помилка", "Один або кілька файлів - не вибрано");
			return View();
		}

		public void ScanForIssues()
		{
			if (_pidholoskoIssueList.Count <= 0)
			{
				try
				{
					DirectoryInfo dI = new DirectoryInfo(Server.MapPath("/Content/Magazine"));
					FileInfo[] filesList = dI.GetFiles("*.pdf");

					string currentIssueNumberPattern = @"^\d+";
					string generalIssueNumberPattern = @"\(\d+\)";
					string issuePublicationMonthPattern = @"-[01]?[0-9]";
					string issuePublicationYearPattern = @".[0-9]{4}";

					foreach (FileInfo f in filesList)
					{
						Regex issueFileNameParse = new Regex(currentIssueNumberPattern);
						Match currentIssueNumber = issueFileNameParse.Match(f.Name);

						issueFileNameParse = new Regex(generalIssueNumberPattern);
						string generalIssueNumber = issueFileNameParse.Match(f.Name).Value;
						generalIssueNumber = generalIssueNumber.Replace("(", "");
						generalIssueNumber = generalIssueNumber.Replace(")", "");

						issueFileNameParse = new Regex(issuePublicationMonthPattern);
						string issuePublicationMonth = issueFileNameParse.Match(f.Name).Value;
						issuePublicationMonth = issuePublicationMonth.Replace("-", "");

						issueFileNameParse = new Regex(issuePublicationYearPattern);
						string issuePublicationYear = issueFileNameParse.Match(f.Name).Value;
						issuePublicationYear = issuePublicationYear.Replace(".", "");

						_pidholoskoIssueList.Add(new pidholoskoMagazineIssue
						{
							numberThisYear = Convert.ToInt16(currentIssueNumber.Value),
							numberGeneral = Convert.ToInt16(generalIssueNumber),
							publicationDate = new DateTime(Convert.ToInt16(issuePublicationYear), Convert.ToInt16(issuePublicationMonth), 1),
							fileUrl = "/Content/Magazine/" + f.Name
						});
					}
				}
				finally
				{
					_pidholoskoIssueList = _pidholoskoIssueList.OrderByDescending(x => x.publicationDate).ToList();
				}
			}
		}
	}
}

studProfkom/Controllers/ProjectsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using studProfkom.Models;

namespace studProfkom.Controllers
{
	public class ProjectsController : Controller
	{
		//
		// GET: /Projects/
		private static List<MissUad> _missList = new List<MissUad>();

		public ProjectsController()
		{
			if (_missList.Count == 0)
			{
				_missList.Add(new MissUad { FirstName = "Наталія", LastName = "Ковтун", Faculty = "ФЕОКС", WinningYear = 2001 });
				_missList.Add(new MissUad { FirstName = "Людмила", LastName = "Ясінська", Faculty = "ФВПІТ", WinningYear = 2002 });
				_missList.Add(new MissUad { FirstName = "Катерина", LastName = "Ішутіна", Faculty = "ФЕОКС", WinningYear = 2003 });
				_missList.Add(new MissUad { FirstName = "Євгенія", LastName = "Бондаренко", Faculty = "ФЕОКС", WinningYear = 2004 });
				_missList.Add(new MissUad { FirstName = "Наталія", LastName = "Червінчак", Faculty = "ФЕОКС", WinningYear = 2005 });
				_missList.Add(new MissUad { FirstName = "Тетяна", LastName = "Мусянович", Faculty = "ФЕОКС", WinningYear = 2006 });
				_missList.Add(new MissUad { FirstName = "Віра", LastName = "Дутчак", Faculty = "ФЕОКС", WinningYear = 2007 });
				_missList.Add(new MissUad { FirstName = "Валерія", LastName = "Гольцева", Faculty = "ФВПІТ", WinningYear = 2008 });
				_missList.Add(new MissUad { FirstName = "Ольга", LastName = "Возняк", Faculty = "ФЕОКС", WinningYear = 2009 });
				_missList.Add(new MissUad { FirstName = "Оксана", LastName = "Секрет", Faculty = "ФЕОКС", WinningYear = 2010 });
				_missList.Add(new MissUad { FirstName = "Анастасія", LastName = "Мацех", Faculty = "ФЕОКС", WinningYear = 2011 });
				_missList.Add(new MissUad { FirstName = "Анастасія", LastName = "Дричик", Faculty = "ЛПК УАД", WinningYear = 2012 });
				_missList = _missList.OrderBy(x => x.WinningYear).ToList();
			}
		}

		public ActionResult MissUad()
		{
			return View(_missList);
		}
		public ActionResult Parties()
		{
			return View();
		}
		public ActionResult SportEvents()
		{
			return View();
		}
		public ActionResult TravelWithUs()
		{
			return View();
		}
		public ActionResult SummerRecovery()
		{
			return View();
		}
		public ActionResult StudentTheater()
		{
			return View();
		}
		public ActionResult StudentArt()
		{
			return View();
		}
		public ActionResult EasterAction()
		{
			return View();
		}
		public ActionResult UkrainianWritingDay()
		{
			return View();
		}
		public ActionResult ScrabbleTourney()
		{
			return View();
		}
		public ActionResult UadTv()
		{
			return View();
		}
		public ActionResult Karaoke()
		{
			return View();
		}
		public ActionResult Charity()
		{
			return View();
		}
	}
}

studProfkom/Views/_mainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
  <title>@ViewBag.Title</title>
  <meta charset="windows-1351"/>
  <meta name=viewport content="width=1024, initial-scale=0">
  <meta name="google-site-verification" content="4QWy8ctb94ROeUCWc2lb8VJMFHLPl5JckFXM-afXMc0" />
  <meta name="keywords" content="Профком УАД, Профком, УАД, Профком студентів УАД" />
  <link rel="shortcut icon" href="@Url.Content("~/Content/Images/favicon.ico")" >
  @if (ViewContext.Controller.ValueProvider.GetValue("controller").RawValue.ToString() == "Profkom")
  {
    @Styles.Render("~/content/bootstrap")
  }
  else
  {
    @Styles.Render("~/content/css")
  }
  @RenderSection("CSSIncludes", false)
</head>
<body>
  <div class="page-wrapper">
    <header>
      <a class="header-logo" href="@Url.Action("Index", "Home")">
        <img src="~/Content/Images/profkom-logo.jpg" />
      </a>
      <div class="header-logo-caption"></div>

      @if (!base.User.Identity.IsAuthenticated)
      {
        @Html.ActionLink("Увійти в систему", "Login", "Account", null, new { @class = "login-btn" })
      }
      else
      {
        <div class="login-btn">Ви увійшли, як <b>@base.User.Identity.Name</b>. @Html.ActionLink("Вийти", "LogOff", "Account")</div>
      }
    </header>
    <div class="white-container">
      <nav>
        <ul class="top-nav-menu">
          <li class="first">
            @Html.ActionLink("ГОЛОВНА", "Index", "Home")
          </li>
          <li class="sub-menu-holder">
            @Html.ActionLink("ПРОФКОМ", "Guidance", "Profkom")
            <ul class="top-nav-sub-menu first-level">
              @*<li>
                <a href="" class="sub-menu-holder">Студенту</a>
                <span class="sub-menu-arrow"></span>
                <ul class="top-nav-sub-menu second-level">
                  <li></li>
                  <li><a href="">One</a></li>
                  <li><a href="">One</a></li>
                  <li><a href="">One</a></li>
                  <li><a href="">One</a></li>
                </ul>
              </li>*@
              <li>@Html.ActionLink("Студентам", "Students", "Profkom")</li>
              <li>@Html.ActionLink("Сиротам", "Orphans", "Profkom")</li>
              <li>@Html.ActionLink("Гуртожитки", "Chummeries", "Profkom")</li>
              <li>@Html.ActionLink("Керівництво", "Guidance", "Profkom")</li>
              <li>@Html.ActionLink("Голови профбюро", "Profbureau", "Profkom")</li>
              <li class="last">@Html.ActionLink("Про нас", "About", "Profkom")</li>
            </ul>
          </li>
          <li class="sub-menu-holder">
            @Html.ActionLink("ПРОЕКТИ", "MissUad", "Projects")
            <ul class="top-nav-sub-menu first-level">
              <li>@Html.ActionLink("Міс УАД", "MissUad", "Projects")</li>
              <li>@Html.ActionLink("Вечірки", "Parties", "Projects")</li>
              <li>@Html.ActionLink("Спортивні досягнення", "SportEvents", "Projects")</li>
              <li>@Html.ActionLink("Подорожуємо разом", "TravelWithUs", "Projects")</li>
              <li>@Html.ActionLink("Літнє оздоровлення", "SummerRecovery", "Projects")</li>
              <li>@Html.ActionLink("Студентський театр", "StudentTheater", "Projects")</li>
              <li>@Html.ActionLink("Фестивалі студентської творчості", "StudentArt", "Projects")</li>
              <li>@Html.ActionLink("Великодні акції", "EasterAction", "Projects")</li>
              <li>@Html.ActionLink("До дня української мови та писемності", "UkrainianWritingDay", "Projects")</li>
              <li>@Html.ActionLink("Турнір зі SCRABBLE", "ScrabbleTourney", "Projects")</li>
              <li>@Html.ActionLink("УАД ТВ - Студентське телебачення", "UadTv", "Projects")</li>
              <li>@Html.ActionLink("Караоке в поліграфі", "Karaoke", "Projects")</li>
              <li class="last">@Html.ActionLink("Благочинність", "Charity", "Projects")</li>
            </ul>
          </li>
          <li>
            @Html.ActionLink("ГАЛЕРЕЯ", "Gallery", "Home")
          </li>
          <li>
            @Html.ActionLink("ГАЗЕТА", "Archive", "PidholoskoMagazine")
          </li>
          <li>
            @Html.ActionLink("КОНТАКТИ", "Contacts", "Home")
          </li>
        </ul>
      </nav>
      <div class="panes-wrapper">
        <div class="left-pane">
          @RenderBody()
        </div>
        <div class="right-pane">

          @{Html.RenderAction("EventsWidget", "Home");}

          <div class="partner-links">
            <h3>НАШІ ГРУПИ У <span>VK.COM</span></h3>
            <a href="http://vk.com/uadtv">
              <img src="@Url.Content("~/Content/Images/uad-tv-logo.jpg")" />
            </a>
            <a href="http://vk.com/studprofkomuad">
              <img src="@Url.Content("~/Content/Images/profkom-vk-logo.jpg")" />
            </a>
            <a href="http://vk.com/uadlviv">
              <img src="@Url.Content("~/Content/Images/uad-vk-logo.jpg")" />
            </a>
          </div>
        </div>
      </div>
      <div class="footer">
        <ul class="footer-menu">
          <li class="first">@Html.ActionLink("ГОЛОВНА", "Index", "Home")</li>
          <li>@Html.ActionLink("ПРОФКОМ", "Guidance", "Profkom")</li>
          <li>@Html.ActionLink("ПРОЕКТИ", "MissUad", "Projects")</li>
          <li>@Html.ActionLink("ГАЛЕРЕЯ", "Gallery", "Home")</li>
          <li>@Html.ActionLink("ГАЗЕТА", "Archive", "PidholoskoMagazine")</li>
          <li>@Html.ActionLink("КОНТАКТИ", "Contacts", "Home")</li>
        </ul>
      </div>
    </div>
  </div>
  @using System.Web.Optimization
  @using StackExchange.Profiling

  @Scripts.Render("~/content/js")
  <a href="https://plus.google.com/113056928089793738016" rel="publisher">Google+</a>

  @RenderSection("JSIncludes", false)
  @MiniProfiler.RenderIncludes()
</body>
</html>